config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    resources :products do
        member do
            post :add_to_cart
        end
    end

    namespace :admin do
        resources :products do
            member do
                post :hide
                post :publish
            end
        end
        resources :orders
    end

    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :cancell
            post :ship
        end
    end

    resources :carts do
        collection do
            post :checkout
        end
    end
    namespace :account do
        resources :orders do
            member do
                post :cancell
            end
        end
    end
    resources :cart_items do
        member do
            post :add
            post :minus
        end
    end

    root 'products#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items, source: :product
    def add_product_to_cart(product)
        ci = cart_items.build
        ci.product = product
        ci.quantity = 1
        ci.save
    end

    def total_price
        sum = 0
        cart_items.each do |cart_item|
            sum += cart_item.quantity * cart_item.product.price
        end
        sum
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        @carts = Cart.all
    end

    def new
        @cart = Cart.new
    end

    def edit
        @cart = Cart.find(params[:id])
    end

    def show
        @cart = Cart.find(params[:id])
    end

    def destroy
        @cart = Cart.find(params[:id])
        @cart.destroy
        redirect_to carts_path
    end

    def checkout
        @order = Order.new
    end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/views/carts/checkout.html.erb
<div class="row">
   <div class="col-md-12">

    <h2> 购物明细 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明细</th>
          <th>单价</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>

            <td>
              <%= cart_item.quantity %>
            </td>

          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        总计 <%= render_cart_total_price(current_cart) %> CNY
      </span>
    </div>

    <hr>

      <h2> 订单资讯 </h2>

      <div class="order-form">

        <%= simple_form_for @order do |f| %>

            <legend> 订购人</legend>
            <div class="form-group col-lg-6">
              <%= f.input :billing_name  %>
            </div>
            <div class="form-group col-lg-6">
              <%= f.input :billing_address  %>
            </div>

            <legend> 收货人</legend>
            <div class="form-group col-lg-6">
             <%= f.input :shipping_name  %>
            </div>
            <div class="form-group col-lg-6">
              <%= f.input :shipping_address  %>
            </div>

          <div class="checkout">
            <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                         data: { disable_with: "Submitting..." } %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">

    <h2> 购物车 </h2>
     <div class="pull-right">
          <%= link_to("清空购物车", cart_path(current_cart), method: :delete, class: "btn btn-sm btn-danger pull-right") %>
     </div>


  <table class="table table-bordered">
    <thead>
        <tr>
           <th colspan="2"> 商品资讯 </th>
           <th> 单价 </th>
           <th> 数量 </th>
           <th> 删除 </th>
        </tr>
    </thead>

    <tbody>
      <% current_cart.cart_items.each do |cart_item| %>
     <tr>
       <td>
        <%= link_to product_path(cart_item.product) do %>
            <% if cart_item.product.image.present? %>
             <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail")  %>
           <% else %>
             <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")  %>
         <% end %>
         <% end %>
       </td>
       <td>
         <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
       </td>

       <td>
          <%= cart_item.product.price %>
       </td>

       <td>
         <%= link_to("-",minus_cart_item_path(cart_item),method: :post,:class =>"btn btn-primary btn-xs btn-danger")%>
         <%= cart_item.quantity %>
         <% if cart_item.quantity < cart_item.product.quantity%>
         <%= link_to("+",add_cart_item_path(cart_item),method: :post,:class =>"btn btn-primary btn-xs btn-danger")%>
         <% else %>
         库存不足
         <% end %>
       </td>

       <td>
         <%= link_to("删除此项", cart_item_path(cart_item),  :class => "btn btn-xs btn-default", :method => :delete, :data => { :confirm => "Are you sure" }) %>
       </td>
      </tr>
   <% end %>

    </tbody>
  </table>

      <br>

      <div class="total clearfix">
         <span class="pull-right">
              <span>
                总计 <%= render_cart_total_price(current_cart) %> RMB
               </span>
         </span>
      </div>

      <hr>

      <div class="checkout clearfix">
         <%= link_to("确认结账", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
      </div>
  </div>
</div>