config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    resources :products do
        member do
            post :add_to_cart
        end
    end

    namespace :admin do
        resources :products do
            member do
                post :hide
                post :publish
            end
        end
        resources :orders
    end

    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :cancell
            post :ship
        end
    end

    resources :carts do
        collection do
            post :checkout
        end
    end
    namespace :account do
        resources :orders do
            member do
                post :cancell
            end
        end
    end
    resources :cart_items do
        member do
            post :add
            post :minus
        end
    end

    root 'products#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  quantity    :integer
#  price       :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string
#

class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
    def hide!
        self.is_hidden = true
        save
    end

    def publish!
        self.is_hidden = false
        save
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_is_admin

    layout 'admin'

    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            flash[:notice] = 'Create Success'
            redirect_to admin_products_path
        else
            render :new
        end
    end

    def show
        @product = Product.find(params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to admin_products_path, notice: 'Update Success'
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to admin_products_path
        flash[:alert] = 'Product Deleted'
    end

    def hide
        @product = Product.find(params[:id])
        @product.hide!
        redirect_to :back
    end

    def publish
        @product = Product.find(params[:id])
        @product.publish!
        redirect_to :back
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :quantity, :price, :image, :is_hidden)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.where(is_hidden: false)
    end

    def show
        @product = Product.find(params[:id])
    end

    def add_to_cart
        @product = Product.find(params[:id])
        current_cart.add_product_to_cart(@product)
        redirect_to :back
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def render_product_status(product)
        if product.is_hidden
            link_to(content_tag(:span, '', class: 'fa fa-lock'), publish_admin_product_path(product), method: :post, class: 'btn btn-xs')

        else
            link_to(content_tag(:span, '', class: 'fa fa-level-down'), hide_admin_product_path(product), method: :post, class: 'btn btn-xs')
        end
    end
end

app/views/admin/products/edit.html.erb
<h2>Edit <%= @product.title %></h2>
<hr>

<%= simple_form_for [:admin,@product] do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :quantity %>

<% if @product.image.present? %>
<span>目前商品图片</span><br>
<%= image_tag(@product.image.thumb.url)%>
<% end %>
<%= f.input :image,as: :file %>
<%= f.input :is_hidden%>

<%= f.submit "Submit" %>
<% end %>

app/views/admin/products/index.html.erb
<div class="col-md-12">
  <h2 class="text-center">Product List</h2>
  <div class="group">
    <%= link_to("New Product",new_admin_product_path,class:"btn btn-link")%>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th width="220">Product Pic</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>

        <td>
          <%= render_product_status(product)%>
          <%= product.id%></td>
        <td>
          <%= link_to admin_product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to(product.title,admin_product_path(product))%></td>
        <td><%= simple_format(product.description)%></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product),class:"btn btn-sm btn-default") %>
          <%= link_to("Delete", admin_product_path(product),class:"btn btn-sm btn-default",method: :delete,data:{confirm:"Are you sure?"}) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<h2>New Product</h2>
<hr>

<%= simple_form_for [:admin,@product] do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :quantity %>
<%= f.input :image,as: :file %>
<%= f.input :is_hidden%>
<%= f.submit "Submit" %>
<% end %>

app/views/admin/products/show.html.erb
<div class="row">
<div class="col-md-6">
  <% if @product.image.present? %>
      <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2> <%= @product.title %> </h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div> 数量 : <%= @product.quantity %> </div>
    <div class="product-price"> ￥ <%= @product.price %> </div>
</div>
</div>