config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    resources :products do
        member do
            post :add_to_cart
        end
    end

    namespace :admin do
        resources :products do
            member do
                post :hide
                post :publish
            end
        end
        resources :orders
    end

    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :cancell
            post :ship
        end
    end

    resources :carts do
        collection do
            post :checkout
        end
    end
    namespace :account do
        resources :orders do
            member do
                post :cancell
            end
        end
    end
    resources :cart_items do
        member do
            post :add
            post :minus
        end
    end

    root 'products#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  quantity    :integer
#  price       :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string
#

class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
    def hide!
        self.is_hidden = true
        save
    end

    def publish!
        self.is_hidden = false
        save
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_is_admin

    layout 'admin'

    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            flash[:notice] = 'Create Success'
            redirect_to admin_products_path
        else
            render :new
        end
    end

    def show
        @product = Product.find(params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to admin_products_path, notice: 'Update Success'
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to admin_products_path
        flash[:alert] = 'Product Deleted'
    end

    def hide
        @product = Product.find(params[:id])
        @product.hide!
        redirect_to :back
    end

    def publish
        @product = Product.find(params[:id])
        @product.publish!
        redirect_to :back
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :quantity, :price, :image, :is_hidden)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.where(is_hidden: false)
    end

    def show
        @product = Product.find(params[:id])
    end

    def add_to_cart
        @product = Product.find(params[:id])
        current_cart.add_product_to_cart(@product)
        redirect_to :back
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def render_product_status(product)
        if product.is_hidden
            link_to(content_tag(:span, '', class: 'fa fa-lock'), publish_admin_product_path(product), method: :post, class: 'btn btn-xs')

        else
            link_to(content_tag(:span, '', class: 'fa fa-level-down'), hide_admin_product_path(product), method: :post, class: 'btn btn-xs')
        end
    end
end

app/views/products/index.html.erb
<h2 class="text-center">Product List</h2>
<div class="row">
  <% @products.each do |product| %>
  <div class="col-xs-6 col-md-3">
    <%= link_to product_path(product) do%>
    <% if product.image.present? %>
    <%= image_tag(product.image.thumb.url, class:"thumbnail")%>
    <% else %>
    <%= image_tag("http://placehold.it/200x200&text=No pic",class:"thumbnail")%>
    <% end %>
    <% end %>
    <%= product.title%><br>
    ¥<%= product.price%>
  </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
<div class="col-md-6">
  <% if @product.image.present? %>
      <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2> <%= @product.title %> </h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div> 数量 : <%= @product.quantity %> </div>
    <div class="product-price"> ￥ <%= @product.price %> </div>
    <div class="pull-right">
      <%= link_to("加入购物车", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-primary btn-lg btn-danger") %>
    </div>
</div>
</div>