config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    resources :products do
        member do
            post :add_to_cart
        end
    end

    namespace :admin do
        resources :products do
            member do
                post :hide
                post :publish
            end
        end
        resources :orders
    end

    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :cancell
            post :ship
        end
    end

    resources :carts do
        collection do
            post :checkout
        end
    end
    namespace :account do
        resources :orders do
            member do
                post :cancell
            end
        end
    end
    resources :cart_items do
        member do
            post :add
            post :minus
        end
    end

    root 'products#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
<% user_facing_flashes.each do |key,value| %>
<div class="alert alert-dismissable alert-<%= flash_class(key) %>">
  <button class="close" data-dismiss="alert">×</button>
  <%= value %>
</div>
<% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px">
  <p class="text-center">Copyright ©2016 JDstore
    <br>Design by
    <a href="#" target=_new>Lydia</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">JDstore</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li class="active">
            <%= link_to("Products", products_path) %>
         </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to carts_path do %>
             购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
          <% end %>
        </li>
        <% if !current_user %>
        <li><%= link_to("注册",new_user_registration_path) %></li>
        <li><%= link_to("登陆",new_user_session_path) %></li>
        <% else %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!<%= current_user.email %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
              <%if current_user.admin? %>
              <li><%= link_to("All Orders",admin_orders_path) %></li>
              <li><%= link_to("Admin Panel",admin_products_path) %></li>
              <% end %>
              <li><%= link_to("我的订单",account_orders_path)%></li>
              <li><%= link_to("登出",destroy_user_session_path,method: :delete)%></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>